default:  fxctmp9_tmp\sdk_flashlight_ps20.inc shaders\fxc\sdk_flashlight_ps20.vcs fxctmp9_tmp\sdk_flashlight_ps20b.inc shaders\fxc\sdk_flashlight_ps20b.vcs fxctmp9_tmp\gstring_light_volumetrics_ps20b.inc shaders\fxc\gstring_light_volumetrics_ps20b.vcs fxctmp9_tmp\gstring_light_volumetrics_vs20.inc shaders\fxc\gstring_light_volumetrics_vs20.vcs

fxctmp9_tmp\sdk_flashlight_ps20.inc shaders\fxc\sdk_flashlight_ps20.vcs: sdk_flashlight_ps2x.fxc common_fxc.h shader_constant_register_map.h common_ps_fxc.h common_vertexlitgeneric_dx9.h common_lightmappedgeneric_fxc.h common_pragmas.h common_hlsl_cpp_consts.h common_flashlight_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." sdk_flashlight_ps2x.fxc-----sdk_flashlight_ps20
	echo sdk_flashlight_ps2x.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo shader_constant_register_map.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_vertexlitgeneric_dx9.h>> filestocopy.txt
	echo common_lightmappedgeneric_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_flashlight_fxc.h>> filestocopy.txt

fxctmp9_tmp\sdk_flashlight_ps20b.inc shaders\fxc\sdk_flashlight_ps20b.vcs: sdk_flashlight_ps2x.fxc common_fxc.h shader_constant_register_map.h common_ps_fxc.h common_vertexlitgeneric_dx9.h common_lightmappedgeneric_fxc.h common_pragmas.h common_hlsl_cpp_consts.h common_flashlight_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." sdk_flashlight_ps2x.fxc-----sdk_flashlight_ps20b
	echo sdk_flashlight_ps2x.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo shader_constant_register_map.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_vertexlitgeneric_dx9.h>> filestocopy.txt
	echo common_lightmappedgeneric_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_flashlight_fxc.h>> filestocopy.txt

fxctmp9_tmp\gstring_light_volumetrics_ps20b.inc shaders\fxc\gstring_light_volumetrics_ps20b.vcs: gstring_light_volumetrics_ps20b.fxc common_fxc.h common_hlsl_cpp_consts.h common_pragmas.h common_flashlight_fxc.h common_ps_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." gstring_light_volumetrics_ps20b.fxc-----gstring_light_volumetrics_ps20b
	echo gstring_light_volumetrics_ps20b.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_flashlight_fxc.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt

fxctmp9_tmp\gstring_light_volumetrics_vs20.inc shaders\fxc\gstring_light_volumetrics_vs20.vcs: gstring_light_volumetrics_vs20.fxc common_fxc.h common_hlsl_cpp_consts.h common_pragmas.h common_vs_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." gstring_light_volumetrics_vs20.fxc-----gstring_light_volumetrics_vs20
	echo gstring_light_volumetrics_vs20.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt

